# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 401)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background:#ffffff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_logo = QtWidgets.QLabel(self.centralwidget)
        self.lb_logo.setGeometry(QtCore.QRect(10, 0, 621, 70))
        self.lb_logo.setStyleSheet("background:#ffffff")
        self.lb_logo.setText("")
        self.lb_logo.setObjectName("lb_logo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 70, 631, 8))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:#26a9e1")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(80, 90, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(410, 90, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn_close.setFont(font)
        self.btn_close.setObjectName("btn_close")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(240, 90, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_stop.setFont(font)
        self.btn_stop.setObjectName("btn_stop")
        self.te_log = QtWidgets.QTextEdit(self.centralwidget)
        self.te_log.setGeometry(QtCore.QRect(10, 140, 611, 231))
        self.te_log.setObjectName("te_log")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 0, 411, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: #333333;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: #26a9e1;\n"
"}")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 630, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.act_settings = QtWidgets.QAction(MainWindow)
        self.act_settings.setObjectName("act_settings")
        self.menuFile.addAction(self.act_settings)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Discord DM Bot"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_close.setText(_translate("MainWindow", "Close"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Discord DM BOT"))
        self.label_2.setText(_translate("MainWindow", "2021.10"))
        self.menuFile.setTitle(_translate("MainWindow", "Settings"))
        self.act_settings.setText(_translate("MainWindow", "Settings"))
